apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-api.fullname" . }}-secret
  labels:
    {{- include "rag-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  gemini-api-key: {{ .Values.secrets.geminiApiKey | quote }}
