{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  labels:
    {{- include "rag-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  type: {{ .Values.qdrant.service.type }}
  ports:
  - port: {{ .Values.qdrant.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.qdrant.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "rag-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
{{- end }}
